server:
  port: 8002
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: cloud-provider
  servlet:  #文件上传
    multipart:
      enabled: true # 开启http文件上传
      max-request-size: 1000MB #设置最大的请求大小，默认10MB，若不限制配置为-1
      max-file-size: 100MB #设置单个文件上传的最大长度，默认是1MB，若不限制配置为-1
#eureka
eureka:
  client: #
    security:
      basic:
        user: admin
        password: admin
    service-url:
      #defaultZone: http://${eureka.client.security.basic.user}:${eureka.client.security.basic.password}@127.0.0.1:8761/eureka
      defaultZone: http://eureka.didispace.com/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10 # 表示eureka client发送心跳给server端的频率(默认30s)
    lease-expiration-duration-in-seconds: 30 # 表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance。（默认90s）
    instance-id: ${spring.application.name}-${server.port}  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 注册中心显示ip

info:  #注册信息
  app.name: cloud-provider-B
  company.name: com.rui.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$
