server:
  port: 8080
spring:
  application:
    name: cloud-gateway-auth
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #\u5F00\u542F\u4E0E\u670D\u52A1\u53D1\u73B0\u7EC4\u4EF6\u6574\u5408\uFF0C\u901A\u8FC7serviceId\u8F6C\u53D1\u5230\u5177\u4F53\u7684\u670D\u52A1\u5B9E\u4F8B \u9ED8\u8BA4\u662Ffalse
          lowerCaseServiceId: true #\u5F53\u6CE8\u518C\u4E2D\u5FC3\u4E3Aeureka\u65F6\uFF0C\u8BBE\u7F6E\u4E3Atrue\u8868\u793A\u542F\u7528\u5C0F\u5199\u7684serviceId\u8FDB\u884C\u670D\u52A1\u7684\u8DEF\u7531\u8F6C\u53D1
      routes:
      #\u6574\u5408eureka\u901A\u8FC7serviceId\u8BBF\u95EE
      - id: consumer_route
        uri: lb://cloud-consumer
        predicates:
        - Path=/cloud-consumer/**
        filters:
        - RewritePath=/cloud-consumer/(?<segment>.*), /$\{segment}
eureka:
  client: # \u5BA2\u6237\u7AEF\u8FDB\u884CEureka\u6CE8\u518C\u7684\u914D\u7F6E
    security:
      basic:
        user: admin
        password: admin
    service-url:
      #defaultZone: http://${eureka.client.security.basic.user}:${eureka.client.security.basic.password}@127.0.0.1:8761/eureka
      defaultZone: http://eureka.springcloud.cn/eureka
  instance:
    lease-renewal-interval-in-seconds: 10 # \u8868\u793Aeureka client\u53D1\u9001\u5FC3\u8DF3\u7ED9server\u7AEF\u7684\u9891\u7387\u3002\u82E5\u5728lease-expiration-duration-in-seconds\u540E\uFF0Cserver\u7AEF\u6CA1\u6709\u6536\u5230client\u7684\u5FC3\u8DF3\uFF0C\u5219\u5C06\u6458\u9664\u8BE5instance\uFF08\u9ED8\u8BA4\u662F30\u79D2\uFF09
    lease-expiration-duration-in-seconds: 30 # \uFF0C\u8868\u793Aeureka server\u81F3\u4E0A\u4E00\u6B21\u6536\u5230client\u7684\u5FC3\u8DF3\u4E4B\u540E\uFF0C\u7B49\u5F85\u4E0B\u4E00\u6B21\u5FC3\u8DF3\u7684\u8D85\u65F6\u65F6\u95F4\uFF08\u9ED8\u8BA4\u662F90\u79D2\uFF09
    instance-id: ${spring.application.name}-${server.port}  # \u5728\u4FE1\u606F\u5217\u8868\u65F6\u663E\u793A\u4E3B\u673A\u540D\u79F0
    prefer-ip-address: true     # \u8BBF\u95EE\u7684\u8DEF\u5F84\u53D8\u4E3AIP\u5730\u5740

info:  #\u8BBE\u7F6Eeureka\u6CE8\u518C\u4E2D\u5FC3\u5F97info\u4FE1\u606F
  app.name: ${spring.application.name}
  company.name: com.rui.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$

# ribbon\u914D\u7F6E
ribbon:
  eager-load:
    enabled: true #ribbob\u5F00\u542F\u997F\u52A0\u8F7D
    clients: CLOUD-CONSUMER,CLOUD-PROVIDER

# hystrix\u914D\u7F6E
hystrix:command.default.execution.isolation.thread.timeoutInMilliseconds: 5000

logging: ## Spring Cloud Gateway\u65E5\u5FD7\u914D\u7F6E
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG