spring:
  application:
    name: auth-server
server:
  port: 7777
  servlet:
    contextPath: /uaa #web基路径
eureka:
  client:
    serviceUrl:
      #defaultZone: http://${eureka.client.security.basic.user}:${eureka.client.security.basic.password}@127.0.0.1:8761/eureka
      defaultZone: http://eureka.springcloud.cn/eureka
  instance:
    prefer-ip-address: true